# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
